In [3]:
import tensorflow as tf

In [4]:
print(tf.__version__)

1.8.0


In [5]:
hello = tf.constant("Hello ")

In [6]:
world = tf.constant("World")

In [7]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [8]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [9]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [10]:
result

b'Hello World'

In [11]:
a = tf.constant(10)

In [12]:
b = tf.constant(20)

In [13]:
type(a)

tensorflow.python.framework.ops.Tensor

In [14]:
a + b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [15]:
a + b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [16]:
a + b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [17]:
with tf.Session() as sess:
    result = sess.run(a + b)

In [18]:
result

30

In [19]:
const = tf.constant(10)

In [21]:
fill_mat = tf.fill((4,4),10)

In [22]:
myzeros = tf.zeros((4,4))

In [23]:
myones = tf.ones((4,4))

In [35]:
myrandn = tf.random_normal((4,4),mean=0,stddev=1.0)

In [36]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [37]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

In [38]:
sess = tf.InteractiveSession()

In [42]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 1.2194084   0.5616701   0.36383483  0.10967357]
 [-0.3327531   0.81062406  0.21712345  0.58387214]
 [ 2.4652994   0.01526544  0.60600185  0.09011413]
 [-0.70533985  0.17967692  0.8030725   1.0725528 ]]


[[0.19119453 0.31258118 0.658718   0.7125735 ]
 [0.8993561  0.3130138  0.29605687 0.9951842 ]
 [0.760164   0.88201237 0.92430747 0.3033638 ]
 [0.90569997 0.43538415 0.13695431 0.71692336]]




In [43]:
a = tf.constant([ [1,2],
                  [3,4] ])

In [44]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [46]:
b = tf.constant([[10] , [100]])

In [47]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [48]:
result = tf.matmul(a,b)

In [50]:
sess.run(result)

array([[210],
       [430]], dtype=int32)

In [51]:
result.eval()

array([[210],
       [430]], dtype=int32)